## Pandas Lab Exercise (Kaggle Automobile Dataset)

We shall now test your skills in using Pandas package. We will be using the [automobiles Dataset](https://www.kaggle.com/nisargpatel/automobiles/data) from Kaggle. 

Answer each question asked below wrt the automobiles dataset. Load pandas as pd and upload the Automobile.csv file as auto

In [11]:
import pandas as pd
import numpy as np
auto=pd.read_csv(r"C:\Users\Lenovo\Downloads\Automobile.csv")
auto

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

**Load the Automobile dataset into variable "auto"**

In [2]:
auto

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

**Check the head of the DataFrame.**

In [3]:
auto.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

**How many rows and columns are there?**

In [14]:
rows,columns=auto.shape
print(rows,columns)

201 26

**What is the average Price of all cars in the dataset?**

In [15]:
d=auto.groupby('make')['price'].mean()
d

make
alfa-romero      15498.333333
audi             17859.166667
bmw              26118.750000
chevrolet         6007.000000
dodge             7875.444444
honda             8184.692308
isuzu             8916.500000
jaguar           34600.000000
mazda            10652.882353
mercedes-benz    33647.000000
mercury          16503.000000
mitsubishi        9239.769231
nissan           10415.666667
peugot           15489.090909
plymouth          7963.428571
porsche          31400.500000
renault           9595.000000
saab             15223.333333
subaru            8541.250000
toyota            9885.812500
volkswagen       10077.500000
volvo            18063.181818
Name: price, dtype: float64

**Which is the cheapest make and costliest make of car in the lot?**

In [19]:
e=auto.groupby('make')['price']
cheap=e.min().idxmin()
cost=e.max().idxmax()
print(cheap) 
print(cost)

subaru
mercedes-benz

**How many cars have horsepower greater than 100?**

In [20]:
hp=df[df['horsepower']>100]
hp

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

**How many hatchback cars are in the dataset ?**

In [24]:
hc=df[df['body_style']=='hatchback']
hc

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500
17,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151
18,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6295
20,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,9988
173,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,11248
174,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,20,24,16558
175,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,19,24,15998
186,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90,5500,24,29,9980

**What are the 3 most commonly found cars in the dataset?**

**Someone purchased a car for 7099, what is the make of the car?**

**Which cars are priced greater than 40000?**

**Which are the cars that are both a sedan and priced less than 7000?**

 **Count the number of unique values in the `fuel_type` column.**

**List all the cars that have a horsepower between 100 and 200, and display their `make`, `horsepower`, and `price`.**

**Find the average `city_mpg` and `highway_mpg` for each `body_style`.**

**What is the median `price` for each `make`?**

**List all cars that have a `wheel_base` greater than 100 and a `curb_weight` less than 2500.**

In [34]:
a=df[(df["wheel_base"]>100) & (df["curb_weight"]<2500)]
print(a)

     symboling  normalized_losses    make fuel_type aspiration  \
9            2                192     bmw       gas        std
10           0                192     bmw       gas        std
169         -1                 65  toyota       gas        std
170         -1                 65  toyota    diesel      turbo
171         -1                 65  toyota       gas        std
172         -1                 65  toyota       gas        std
173         -1                 65  toyota       gas        std

    number_of_doors body_style drive_wheels engine_location  wheel_base  ...  \
9               two      sedan          rwd           front       101.2  ...
10             four      sedan          rwd           front       101.2  ...
169            four      sedan          fwd           front       102.4  ...
170            four      sedan          fwd           front       102.4  ...
171            four  hatchback          fwd           front       102.4  ...
172            four      sedan          fwd           front       102.4  ...
173            four  hatchback          fwd           front       102.4  ...

     engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
9            108         mpfi  3.50    2.80               8.8        101
10           108         mpfi  3.50    2.80               8.8        101
169          122         mpfi  3.31    3.54               8.7         92
170          110          idi  3.27    3.35              22.5         73
171          122         mpfi  3.31    3.54               8.7         92
172          122         mpfi  3.31    3.54               8.7         92
173          122         mpfi  3.31    3.54               8.7         92

     peak_rpm city_mpg  highway_mpg  price
9        5800       23           29  16430
10       5800       23           29  16925
169      4200       29           34   8948
170      4500       30           33  10698
171      4200       27           32   9988
172      4200       27           32  10898
173      4200       27           32  11248

[7 rows x 26 columns]

**Create a new column `price_per_hp` that calculates the price of the car per horsepower.**

**Count how many cars have a `number_of_doors` as `four`.**

In [28]:
noofdoor=df[df['number_of_doors']=="four"]
#noofdoor
len(noofdoor)

114

**Find the top 5 cars based on their `highway_mpg` and `price`.**

In [35]:
# Sort by 'highway_mpg' and 'price' in descending order
top_5_cars = df.sort_values(by=['highway_mpg', 'price'], ascending=[False, False])

# Select the top 5 rows
top_5_cars = top_5_cars.head(5)

# Display the top 5 cars
print(top_5_cars)

     symboling  normalized_losses       make fuel_type aspiration  \
29           2                137      honda       gas        std
17           2                121  chevrolet       gas        std
87           1                128     nissan    diesel        std
155          0                 91     toyota    diesel        std
156          0                 91     toyota       gas        std

    number_of_doors body_style drive_wheels engine_location  wheel_base  ...  \
29              two  hatchback          fwd           front        86.6  ...
17              two  hatchback          fwd           front        88.4  ...
87              two      sedan          fwd           front        94.5  ...
155            four  hatchback          fwd           front        95.7  ...
156            four      sedan          fwd           front        95.7  ...

     engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
29            92         1bbl  2.91    3.41               9.6         58
17            61         2bbl  2.91    3.03               9.5         48
87           103          idi  2.99    3.47              21.9         55
155          110          idi  3.27    3.35              22.5         56
156           98         2bbl  3.19    3.03               9.0         70

     peak_rpm city_mpg  highway_mpg  price
29       4800       49           54   6479
17       5100       47           53   5151
87       4800       45           50   7099
155      4500       38           47   7788
156      4800       38           47   7738

[5 rows x 26 columns]

**How many cars have missing values in the `normalized_losses` column?**

**Create a new column `car_age` that calculates the age of the car based on the `year_of_manufacture` (assume the current year is 2025).**

### The END